workspace:
  base: /go
  path: src/code.gitea.io/sdk

clone:
  git:
    image: plugins/git:next
    depth: 50
    tags: true

pipeline:
  testing:
    image: golang:1.12
    pull: true
    commands:
      - make clean
      - make vet
      - make lint
      - make test
      - make build

  # coverage:
  #   image: plugins/coverage:1
  #   pull: true
  #   secrets: [ github_token ]
  #   server: https://coverage.gitea.io

  discord:
    image: appleboy/drone-discord:1.0.0
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure ]
