---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

workspace:
  base: /go
  path: src/code.gitea.io/sdk

steps:
- name: gitea
  image: gitea/gitea:latest
  detach: true
  commands:
  - gitea migrate -c /go/src/code.gitea.io/sdk/drone/app.ini
  - gitea admin create-user --username=test01 --password=test01 --email=test01@gitea.io --admin=true --must-change-password=false --access-token -c /go/src/code.gitea.io/sdk/drone/app.ini
  - gitea web -c /go/src/code.gitea.io/sdk/drone/app.ini

- name: git
  pull: default
  image: plugins/git:next
  settings:
    depth: 50
    tags: true
  when:
    branch:
    - master

- name: testing
  pull: always
  image: golang:1.13
  environment:
    GOPROXY: https://goproxy.cn
    GITEA_SDK_TEST_URL: "http://gitea:3000"
    GITEA_SDK_TEST_USERNAME: "test01"
    GITEA_SDK_TEST_PASSWORD: "test01"
    #GITEA_SDK_TEST_RUN_GITEA: "true"
  commands:
  - make clean
  - make vet
  - make lint
  - make build
  - make test

- name: discord
  pull: always
  image: appleboy/drone-discord:1.0.0
  environment:
    DISCORD_WEBHOOK_ID:
      from_secret: discord_webhook_id
    DISCORD_WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  when:
    event:
    - push
    - tag
    - pull_request
    status:
    - changed
    - failure